-- Create the subcategories and file the existing catalogue into them.
--
-- GENERATED by scripts/generate-classify-migration.ts from
-- src/lib/subcategories.ts. Edit the rules there and regenerate; do not hand-
-- edit this file, and once it has been applied anywhere, do not regenerate it
-- either -- a rule change then needs a new migration that moves the products.
--
-- Each UPDATE only ever fills a row that is still unclassified, applied in
-- rule order, so the first matching rule wins exactly as the TypeScript
-- classifier does. Re-running is harmless: inserts are guarded by ON CONFLICT
-- and updates by "subcategoryId" IS NULL.
--
-- Subcategories with no UPDATE below are deliberate. The shop distinguishes a
-- ceramic pot from a metal one, but the product names do not -- "Aura Pot 10
-- Inch" says nothing about material -- so those are created empty and filed by
-- hand in the admin. An empty subcategory is hidden from the public page, so
-- it costs a customer nothing until it has stock in it.
--
-- Categories absent from this file have no subcategories, which is a decision:
-- Cooler & Fan has four products and Festive & Puja one.


-- ====================================================================
-- Lights & Lighting Décor
-- ====================================================================

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'jhumar', 'Jhumar', '', 0, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Lights & Lighting Décor'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'led-palco-and-strip-light', 'LED, Palco & Strip Light', '', 1, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Lights & Lighting Décor'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'light-stand-and-hanging', 'Light Stand & Hanging', '', 2, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Lights & Lighting Décor'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'imported-light-stand', 'Imported Light Stand', '', 3, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Lights & Lighting Décor'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'imported-hanging-light', 'Imported Hanging Light', '', 4, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Lights & Lighting Décor'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'jhumar' AND c."name" = 'Lights & Lighting Décor'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'chandelier|jhumar';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'led-palco-and-strip-light' AND c."name" = 'Lights & Lighting Décor'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* '\yled\y|palco|strip|par light';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'light-stand-and-hanging' AND c."name" = 'Lights & Lighting Décor'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'light stand|candle stand|x stand|stand \(set|hanging';

-- Imported Light Stand: filed by hand; nothing in a product name identifies it.

-- Imported Hanging Light: filed by hand; nothing in a product name identifies it.

-- ====================================================================
-- Artificial Flowers & Greenery
-- ====================================================================

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'flower-bunch', 'Flower Bunch', '', 0, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Artificial Flowers & Greenery'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'ready-panel', 'Ready Panel', '', 1, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Artificial Flowers & Greenery'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'hanging', 'Hanging', '', 2, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Artificial Flowers & Greenery'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'golden-sticks', 'Golden Sticks', '', 3, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Artificial Flowers & Greenery'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'sticks', 'Sticks', '', 4, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Artificial Flowers & Greenery'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'leaf', 'Leaf', '', 5, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Artificial Flowers & Greenery'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'filler', 'Filler', '', 6, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Artificial Flowers & Greenery'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'loose-flowers', 'Loose Flowers', '', 7, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Artificial Flowers & Greenery'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'flower-bunch' AND c."name" = 'Artificial Flowers & Greenery'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'bunch';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'ready-panel' AND c."name" = 'Artificial Flowers & Greenery'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'panel|ready';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'hanging' AND c."name" = 'Artificial Flowers & Greenery'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'hanging|latta|wisteria';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'golden-sticks' AND c."name" = 'Artificial Flowers & Greenery'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* '(golden|silver).*stick|stick.*(golden|silver)';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'sticks' AND c."name" = 'Artificial Flowers & Greenery'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'stick';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'leaf' AND c."name" = 'Artificial Flowers & Greenery'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'patta|pata|leave|leaf|money plant|satter';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'filler' AND c."name" = 'Artificial Flowers & Greenery'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'filler|pompas|gypsy|pops|poleen';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'loose-flowers' AND c."name" = 'Artificial Flowers & Greenery'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL;

-- ====================================================================
-- Gift Boxes, Trays, Bags & Baskets
-- ====================================================================

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'jar-hampers', 'Jar Hampers', '', 0, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Gift Boxes, Trays, Bags & Baskets'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'tin-jars', 'Tin Jars', '', 1, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Gift Boxes, Trays, Bags & Baskets'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'potli-bags', 'Potli Bags', '', 2, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Gift Boxes, Trays, Bags & Baskets'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'bags-and-purses', 'Bags & Purses', '', 3, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Gift Boxes, Trays, Bags & Baskets'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'trays-and-platters', 'Trays & Platters', '', 4, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Gift Boxes, Trays, Bags & Baskets'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'baskets-and-tokri', 'Baskets & Tokri', '', 5, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Gift Boxes, Trays, Bags & Baskets'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'gift-boxes', 'Gift Boxes', '', 6, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Gift Boxes, Trays, Bags & Baskets'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'other-gifting', 'Other Gifting', '', 7, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Gift Boxes, Trays, Bags & Baskets'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'jar-hampers' AND c."name" = 'Gift Boxes, Trays, Bags & Baskets'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* '^\d+\s*(\+\s*\d+)?\s*jar|^\d+ khana|premium \d+ jar';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'tin-jars' AND c."name" = 'Gift Boxes, Trays, Bags & Baskets'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'tin jar';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'potli-bags' AND c."name" = 'Gift Boxes, Trays, Bags & Baskets'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'potli';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'bags-and-purses' AND c."name" = 'Gift Boxes, Trays, Bags & Baskets'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* '\ybag\y|purse|attachi';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'trays-and-platters' AND c."name" = 'Gift Boxes, Trays, Bags & Baskets'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'tray|platter';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'baskets-and-tokri' AND c."name" = 'Gift Boxes, Trays, Bags & Baskets'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'basket|tokri|balti|cane';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'gift-boxes' AND c."name" = 'Gift Boxes, Trays, Bags & Baskets'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* '\ybox\y';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'other-gifting' AND c."name" = 'Gift Boxes, Trays, Bags & Baskets'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL;

-- ====================================================================
-- Backdrops, Wall Panels & Cloths
-- ====================================================================

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'wall', 'Wall', '', 0, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Backdrops, Wall Panels & Cloths'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'ceiling', 'Ceiling', '', 1, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Backdrops, Wall Panels & Cloths'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'passage', 'Passage', '', 2, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Backdrops, Wall Panels & Cloths'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'table-chair-cover', 'Table - Chair Cover', '', 3, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Backdrops, Wall Panels & Cloths'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'selfie-cloths', 'Selfie Cloths', '', 4, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Backdrops, Wall Panels & Cloths'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'printed-cloth', 'Printed Cloth', '', 5, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Backdrops, Wall Panels & Cloths'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'hanging-cloths-and-backdrops', 'Hanging Cloths & Backdrops', '', 6, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Backdrops, Wall Panels & Cloths'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'plain-cloth', 'Plain Cloth', '', 7, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Backdrops, Wall Panels & Cloths'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'wall' AND c."name" = 'Backdrops, Wall Panels & Cloths'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'wall';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'ceiling' AND c."name" = 'Backdrops, Wall Panels & Cloths'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'ceiling';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'passage' AND c."name" = 'Backdrops, Wall Panels & Cloths'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'passage';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'table-chair-cover' AND c."name" = 'Backdrops, Wall Panels & Cloths'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'table cover|chair cover|counter table';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'selfie-cloths' AND c."name" = 'Backdrops, Wall Panels & Cloths'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'selfie';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'printed-cloth' AND c."name" = 'Backdrops, Wall Panels & Cloths'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'print';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'hanging-cloths-and-backdrops' AND c."name" = 'Backdrops, Wall Panels & Cloths'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'hanging|jhaler|chindi|daman|panel|butta';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'plain-cloth' AND c."name" = 'Backdrops, Wall Panels & Cloths'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'lycra|velvet|roto|micro|galaxy|galexy|net|cloth|foil|mate|grass';

-- ====================================================================
-- Rajasthani & Haldi-Mehndi-Mayra Décor
-- ====================================================================

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'chakri', 'Chakri', '', 0, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Rajasthani & Haldi-Mehndi-Mayra Décor'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'lardi-and-garlands', 'Lardi & Garlands', '', 1, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Rajasthani & Haldi-Mehndi-Mayra Décor'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'tassels-and-pom-poms', 'Tassels & Pom Poms', '', 2, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Rajasthani & Haldi-Mehndi-Mayra Décor'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'umbrellas', 'Umbrellas', '', 3, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Rajasthani & Haldi-Mehndi-Mayra Décor'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'jhumar-and-hangings', 'Jhumar & Hangings', '', 4, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Rajasthani & Haldi-Mehndi-Mayra Décor'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'kites', 'Kites', '', 5, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Rajasthani & Haldi-Mehndi-Mayra Décor'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'other-rajasthani', 'Other Rajasthani', '', 6, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Rajasthani & Haldi-Mehndi-Mayra Décor'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'chakri' AND c."name" = 'Rajasthani & Haldi-Mehndi-Mayra Décor'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'chakri';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'lardi-and-garlands' AND c."name" = 'Rajasthani & Haldi-Mehndi-Mayra Décor'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'lardi';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'tassels-and-pom-poms' AND c."name" = 'Rajasthani & Haldi-Mehndi-Mayra Décor'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'tassal|tussal|pom ?pom|churdi';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'umbrellas' AND c."name" = 'Rajasthani & Haldi-Mehndi-Mayra Décor'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'umbrella';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'jhumar-and-hangings' AND c."name" = 'Rajasthani & Haldi-Mehndi-Mayra Décor'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'jhumar|ring with bell|dream catcher|pankh';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'kites' AND c."name" = 'Rajasthani & Haldi-Mehndi-Mayra Décor'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'kite';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'other-rajasthani' AND c."name" = 'Rajasthani & Haldi-Mehndi-Mayra Décor'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL;

-- ====================================================================
-- Packing & Bouquet Accessories
-- ====================================================================

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'ribbons-bows-and-lace', 'Ribbons, Bows & Lace', '', 0, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Packing & Bouquet Accessories'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'tapes-and-glue', 'Tapes & Glue', '', 1, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Packing & Bouquet Accessories'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'cellophane-and-nets', 'Cellophane & Nets', '', 2, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Packing & Bouquet Accessories'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'papers-and-sheets', 'Papers & Sheets', '', 3, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Packing & Bouquet Accessories'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'sprays-and-moti', 'Sprays & Moti', '', 4, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Packing & Bouquet Accessories'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'ribbons-bows-and-lace' AND c."name" = 'Packing & Bouquet Accessories'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'ribbon|bow|lace';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'tapes-and-glue' AND c."name" = 'Packing & Bouquet Accessories'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'tape|glue';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'cellophane-and-nets' AND c."name" = 'Packing & Bouquet Accessories'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'cellophane|net';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'papers-and-sheets' AND c."name" = 'Packing & Bouquet Accessories'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'paper|sheet|tissue';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'sprays-and-moti' AND c."name" = 'Packing & Bouquet Accessories'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL;

-- ====================================================================
-- Pots & Vases
-- ====================================================================

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'plastic-flower-pot', 'Plastic Flower Pot', '', 0, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Pots & Vases'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'china-pot', 'China Pot', '', 1, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Pots & Vases'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'ceramic-pot', 'Ceramic Pot', '', 2, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Pots & Vases'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'metal-pot', 'Metal Pot', '', 3, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Pots & Vases'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'urli', 'Urli', '', 4, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Pots & Vases'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

-- Plastic Flower Pot: filed by hand; nothing in a product name identifies it.

-- China Pot: filed by hand; nothing in a product name identifies it.

-- Ceramic Pot: filed by hand; nothing in a product name identifies it.

-- Metal Pot: filed by hand; nothing in a product name identifies it.

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'urli' AND c."name" = 'Pots & Vases'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'urli';

-- ====================================================================
-- SFX & Special Effects
-- ====================================================================

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'machine', 'Machine', '', 0, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'SFX & Special Effects'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'pyro', 'Pyro', '', 1, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'SFX & Special Effects'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'paper-and-jari-confetti', 'Paper & Jari Confetti', '', 2, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'SFX & Special Effects'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'liquid-and-powder', 'Liquid & Powder', '', 3, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'SFX & Special Effects'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'machine' AND c."name" = 'SFX & Special Effects'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'machine|wheel|booth';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'pyro' AND c."name" = 'SFX & Special Effects'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'pyro|sparkular';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'paper-and-jari-confetti' AND c."name" = 'SFX & Special Effects'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'confetti';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'liquid-and-powder' AND c."name" = 'SFX & Special Effects'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'co2|gun';
