/**
 * Regenerates the classify_catalogue migration from SUBCATEGORY_RULES.
 *
 * The SQL and the TypeScript classifier are the same rules twice (see
 * src/lib/subcategories.ts), and hand-keeping them in step is exactly the kind
 * of job that produced the \b/\y bug. Generating one from the other removes
 * the transcription step; `npm run check:subcategories` then proves they agree.
 *
 * Only safe to run while the migration has not yet been applied anywhere. Once
 * it has shipped, a rule change needs a NEW migration that moves the affected
 * products — rewriting an applied migration does nothing to a database that
 * already ran it.
 *
 *   npx tsx scripts/generate-classify-migration.ts
 *
 * A rule change after that ships as a DELTA migration instead -- the same
 * generator, narrowed to the categories whose rules moved and written to a new
 * directory, so the SQL is still generated rather than transcribed:
 *
 *   npx tsx scripts/generate-classify-migration.ts \
 *     --dir=prisma/migrations/20261002090000_file_remaining_lights \
 *     --only='Lights & Lighting Décor'
 *
 * A delta is safe to re-run over a live catalogue for the same reason the
 * first one was: inserts are ON CONFLICT DO NOTHING and every UPDATE is
 * guarded by "subcategoryId" IS NULL, so it only ever fills a gap and can
 * never move a product the shop has already filed by hand.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { SUBCATEGORY_RULES, subcategorySlug } from "../src/lib/subcategories";

const arg = (name: string) =>
  process.argv.slice(2).find((a) => a.startsWith(`--${name}=`))?.slice(name.length + 3);

const DIR = join(
  process.cwd(),
  arg("dir") ?? "prisma/migrations/20261001133000_classify_catalogue_into_subcategories",
);

/** Comma-separated category names; omitted means every category. */
const only = arg("only")?.split(",").map((s) => s.trim()).filter(Boolean);

const entries = Object.entries(SUBCATEGORY_RULES).filter(
  ([category]) => !only || only.includes(category),
);

if (only) {
  const unknown = only.filter((c) => !(c in SUBCATEGORY_RULES));
  if (unknown.length > 0) {
    // A typo here would otherwise write a migration that quietly does nothing.
    console.error(`No subcategory rules for: ${unknown.join(", ")}`);
    process.exit(1);
  }
}

const lit = (s: string) => `'${s.replace(/'/g, "''")}'`;
/** POSIX spells a word boundary \y; \b there is a backspace character. */
const toPostgres = (r: RegExp) => r.source.replace(/\\b/g, "\\y");

const FULL_HEADER = `-- Create the subcategories and file the existing catalogue into them.
--
-- GENERATED by scripts/generate-classify-migration.ts from
-- src/lib/subcategories.ts. Edit the rules there and regenerate; do not hand-
-- edit this file, and once it has been applied anywhere, do not regenerate it
-- either -- a rule change then needs a new migration that moves the products.
--
-- Each UPDATE only ever fills a row that is still unclassified, applied in
-- rule order, so the first matching rule wins exactly as the TypeScript
-- classifier does. Re-running is harmless: inserts are guarded by ON CONFLICT
-- and updates by "subcategoryId" IS NULL.
--
-- Subcategories with no UPDATE below are deliberate. The shop distinguishes a
-- ceramic pot from a metal one, but the product names do not -- "Aura Pot 10
-- Inch" says nothing about material -- so those are created empty and filed by
-- hand in the admin. An empty subcategory is hidden from the public page, so
-- it costs a customer nothing until it has stock in it.
--
-- Categories absent from this file have no subcategories, which is a decision:
-- Cooler & Fan has four products and Festive & Puja one.
`;

const deltaHeader = (categories: string[]) => `-- Fill the gaps left in ${categories.join(", ")}.
--
-- GENERATED by scripts/generate-classify-migration.ts from
-- src/lib/subcategories.ts, narrowed to the categories whose rules changed.
-- Do not hand-edit, and do not regenerate once applied.
--
-- Every UPDATE is guarded by "subcategoryId" IS NULL and every INSERT by
-- ON CONFLICT DO NOTHING, so this only ever fills a product that is not filed
-- yet. It cannot move anything the shop placed by hand, and re-running it
-- does nothing the second time.
`;

const out: string[] = [only ? deltaHeader(only) : FULL_HEADER];

for (const [category, rules] of entries) {
  out.push(`\n-- ${"=".repeat(68)}\n-- ${category}\n-- ${"=".repeat(68)}`);

  rules.forEach((rule, order) => {
    out.push(`
INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), ${lit(subcategorySlug(rule.name))}, ${lit(rule.name)}, '', ${order}, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = ${lit(category)}
ON CONFLICT ("categoryId", "slug") DO NOTHING;`);
  });

  for (const rule of rules) {
    if (!rule.catchAll && !rule.pattern) {
      out.push(`\n-- ${rule.name}: filed by hand; nothing in a product name identifies it.`);
      continue;
    }
    const match = rule.catchAll ? "" : `\n  AND p."name" ~* ${lit(toPostgres(rule.pattern!))}`;
    out.push(`
UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = ${lit(subcategorySlug(rule.name))} AND c."name" = ${lit(category)}
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL${match};`);
  }
}

mkdirSync(DIR, { recursive: true });
writeFileSync(join(DIR, "migration.sql"), out.join("\n") + "\n");
console.log(
  `Wrote ${DIR}/migration.sql: ${entries.length} categor${entries.length === 1 ? "y" : "ies"}, ` +
    `${entries.reduce((n, [, r]) => n + r.length, 0)} subcategories.`,
);
