-- Fill the gaps left in Lights & Lighting Décor.
--
-- GENERATED by scripts/generate-classify-migration.ts from
-- src/lib/subcategories.ts, narrowed to the categories whose rules changed.
-- Do not hand-edit, and do not regenerate once applied.
--
-- Every UPDATE is guarded by "subcategoryId" IS NULL and every INSERT by
-- ON CONFLICT DO NOTHING, so this only ever fills a product that is not filed
-- yet. It cannot move anything the shop placed by hand, and re-running it
-- does nothing the second time.


-- ====================================================================
-- Lights & Lighting Décor
-- ====================================================================

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'jhumar', 'Jhumar', '', 0, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Lights & Lighting Décor'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'led-palco-and-strip-light', 'LED, Palco & Strip Light', '', 1, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Lights & Lighting Décor'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'light-stand-and-hanging', 'Light Stand & Hanging', '', 2, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Lights & Lighting Décor'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'imported-light-stand', 'Imported Light Stand', '', 3, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Lights & Lighting Décor'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'imported-hanging-light', 'Imported Hanging Light', '', 4, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Lights & Lighting Décor'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'bulbs-and-holders', 'Bulbs & Holders', '', 5, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Lights & Lighting Décor'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

INSERT INTO "Subcategory" ("id", "slug", "name", "description", "displayOrder", "categoryId", "createdAt", "updatedAt")
SELECT md5(random()::text || clock_timestamp()::text), 'light-panels', 'Light Panels', '', 6, c."id", NOW(), NOW()
FROM "Category" c WHERE c."name" = 'Lights & Lighting Décor'
ON CONFLICT ("categoryId", "slug") DO NOTHING;

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'jhumar' AND c."name" = 'Lights & Lighting Décor'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'chandelier|jhumar';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'led-palco-and-strip-light' AND c."name" = 'Lights & Lighting Décor'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* '\yled\y|palco|strip|par light|cloth light|crock light';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'light-stand-and-hanging' AND c."name" = 'Lights & Lighting Décor'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* 'light stand|candle stand|x stand|stand \(set|hanging|light tree|shell light|light bird|titli bird|sun light \d|\y9\d{2}\y';

-- Imported Light Stand: filed by hand; nothing in a product name identifies it.

-- Imported Hanging Light: filed by hand; nothing in a product name identifies it.

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'bulbs-and-holders' AND c."name" = 'Lights & Lighting Décor'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* '\ybulbs?\y';

UPDATE "Product" p SET "subcategoryId" = s."id"
FROM "Subcategory" s JOIN "Category" c ON c."id" = s."categoryId"
WHERE s."slug" = 'light-panels' AND c."name" = 'Lights & Lighting Décor'
  AND p."categoryId" = c."id"
  AND p."subcategoryId" IS NULL
  AND p."name" ~* '\ypanel\y';
